const games = [
    {
        id: 1,
        title: "FAR CRY 2",
        image: "/assets/far-cry-2.webp",
        category: "Action & Adventure",
        availability: "Now on KGStore",
        price: "Free",
    },
    {
        id: 2,
        title: "EA FC25",
        image: "/assets/fc25.png",
        category: "Sports",
        availability: "Now on KGStore",
        price: "Buy Now",
    },
    {
        id: 3,
        title: "RESIDENT EVIL 4",
        image: "/assets/resident_ev_4.png",
        category: "Horror",
        availability: "Now on KGStore",
        price: "Buy Now",
    },
    {
        id: 4,
        title: "STREET FIGHTER 5",
        image: "/assets/street_fighter_5.png",
        category: "Fighting",
        availability: "Not available",
        price: "Coming Soon",
    },
    {
        id: 5,
        title: "NEED FOR SPEED",
        image: "/assets/n_f_s.png",
        category: "Racing",
        availability: "Not available",
        price: "Coming Soon",
    },
    {
        id: 6,
        title: "HITMAN",
        image: "/assets/hitm.png",
        category: "Action & Adventure",
        availability: "Not available",
        price: "Coming Soon",
    },
    {
        id: 7,
        title: "BLACK MYTH: WUKONG",
        image: "/assets/wukong.png",
        category: "Action & Adventure",
        availability: "Not available",
        price: "Coming Soon",
    },
    {
        id: 8,
        title: "NBA 2K25",
        image: "/assets/nba2k25.png",
        category: "Sports",
        availability: "Available",
        price: "Coming Soon",
    },
    {
        id: 9,
        title: "CYBERPUNK 2077",
        image: "/assets/cyberpunk.png",
        category: "Sci-Fi",
        availability: "Available",
        price: "Coming Soon",
    },
    {
        id: 10,
        title: "ASSASSIN'S CREED SHADOW",
        image: "/assets/shadow.png",
        category: "Action & Adventure",
        availability: "Available",
        price: "Coming Soon",
    },
];

export default games;